# config.tml
[simulation]
fontPath = "resources/3230-font.ttf"
resolution.width = 600
resolution.height = 400
grid = 10
particle.radius = 5.0

[environment]
gravity = { x = 0.0, y = 0.0 }
damping = 0.5
influenceRange = 40.0